[package]
authors = ["Elliott Linder <elliott.darfink@gmail.com>"]
name = "detour"
version = "0.1.0"

[dependencies]
error-chain = "0.7.1"
generic-array = "0.5.1"
lazy_static = "0.2.2"
libc = "0.2.17"
libudis86-sys = "0.1.0"
memmap = "0.5.0"
region = "0.0.5"
