[package]
authors = ["Elliott Linder <elliott.darfink@gmail.com>"]
name = "detour"
version = "0.1.0"

[dependencies]
boolinator = "2.4.0"
cfg-if = "0.1.0"
error-chain = "0.7.1"
generic-array = "0.5.1"
lazy_static = "0.2.2"
libc = "0.2.17"
region = "0.0.5"
slice-pool = "0.3.1"

[dependencies.mmap]
git = "https://github.com/retep998/rust-mmap.git"

[target]

[target."cfg(any(target_arch = \"x86\", target_arch = \"x86_64\"))".dependencies]
libudis86-sys = "0.1.0"
